database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/clevertec_user
  username: postgres
  password: root
cache:
  capacity: 3
  algorithm: LRU
liquibase:
  should_run: true
  changelog_path: classpath:changelog.xml
