Connection.driver: "org.postgresql.Driver"
Connection.url: "jdbc:postgresql://localhost:5432/clevertec_user"
Connection.username: "postgres"
Connection.password: "root"
Cache.capacity: "3"
Cache.algorithm: "LRU"
